config/routes.rb
Rails.application.routes.draw do
  resources :by_months
  resources :by_dates
  resources :brazil_data
  resources :states
  get "/by_dates/search/:initials", to: "by_dates#get_date"

  get "/by_months/search/:initials", to: "by_months#get_month"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/by_date.rb
class ByDate < ApplicationRecord
end

app/models/by_month.rb
class ByMonth < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/by_dates_controller.rb
class ByDatesController < ApplicationController
  before_action :set_by_date, only: %i[ show update destroy ]

  def get_date
    @by_dates = ByDate.where(initials: params[:initials])
    render json: @by_dates
  end  

  # GET /by_dates
  # GET /by_dates.json
  def index
    @by_dates = ByDate.all
  end

  # GET /by_dates/1
  # GET /by_dates/1.json
  def show

  end

  # POST /by_dates
  # POST /by_dates.json
  def create
    @by_date = ByDate.new(by_date_params)

    if @by_date.save
      render :show, status: :created, location: @by_date
    else
      render json: @by_date.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /by_dates/1
  # PATCH/PUT /by_dates/1.json
  def update
    if @by_date.update(by_date_params)
      render :show, status: :ok, location: @by_date
    else
      render json: @by_date.errors, status: :unprocessable_entity
    end
  end

  # DELETE /by_dates/1
  # DELETE /by_dates/1.json
  def destroy
    @by_date.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_by_date
      @by_date = ByDate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def by_date_params
      params.require(:by_date).permit(:name, :initials, :cases, :deaths, :suspects, :datetime)
    end
end

app/controllers/by_months_controller.rb
class ByMonthsController < ApplicationController
  before_action :set_by_month, only: %i[ show update destroy ]

  # GET /by_months
  # GET /by_months.json

  def get_month
    @by_months = ByMonth.where(initials: params[:initials])
    render json: @by_months
  end  

  def index
    @by_months = ByMonth.all
  end

  # GET /by_months/1
  # GET /by_months/1.json
  def show
  end

  # POST /by_months
  # POST /by_months.json
  def create
    @by_month = ByMonth.new(by_month_params)

    if @by_month.save
      render :show, status: :created, location: @by_month
    else
      render json: @by_month.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /by_months/1
  # PATCH/PUT /by_months/1.json
  def update
    if @by_month.update(by_month_params)
      render :show, status: :ok, location: @by_month
    else
      render json: @by_month.errors, status: :unprocessable_entity
    end
  end

  # DELETE /by_months/1
  # DELETE /by_months/1.json
  def destroy
    @by_month.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_by_month
      @by_month = ByMonth.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def by_month_params
      params.require(:by_month).permit(:name, :initials, :cases, :deaths, :suspects, :datetime)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: %i[ show edit update destroy ]

  # GET /states or /states.json
  def index
    @state = State.all
    render json: @state
  end

  # GET /states/1 or /states/1.json
  def show
    render json: @state
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states or /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: "State was successfully created." }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: "State was successfully updated." }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: "State was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:name, :initials, :cases, :deaths, :suspects, :datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyUnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/states/_form.html.erb
<%= form_with(model: state) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
        <% state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :initials %>
    <%= form.text_field :initials %>
  </div>

  <div class="field">
    <%= form.label :cases %>
    <%= form.number_field :cases %>
  </div>

  <div class="field">
    <%= form.label :deaths %>
    <%= form.number_field :deaths %>
  </div>

  <div class="field">
    <%= form.label :suspects %>
    <%= form.number_field :suspects %>
  </div>

  <div class="field">
    <%= form.label :datetime %>
    <%= form.date_select :datetime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Initials</th>
      <th>Cases</th>
      <th>Deaths</th>
      <th>Suspects</th>
      <th>Datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= state.initials %></td>
        <td><%= state.cases %></td>
        <td><%= state.deaths %></td>
        <td><%= state.suspects %></td>
        <td><%= state.datetime %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Initials:</strong>
  <%= @state.initials %>
</p>

<p>
  <strong>Cases:</strong>
  <%= @state.cases %>
</p>

<p>
  <strong>Deaths:</strong>
  <%= @state.deaths %>
</p>

<p>
  <strong>Suspects:</strong>
  <%= @state.suspects %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @state.datetime %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>